replicaCount: 1

image:
  repository: registry.clbs.io/cybroslabs/gpg-encryptor/gpg-encryptor
  tag:
  pullPolicy: IfNotPresent
  pullSecrets: []

resources:
  # limits:
  #   cpu: 500m
  #   memory: 1536Mi
  # requests:
  #   cpu: 200m
  #   memory: 1024Mi

service:
  type: ClusterIP
  port:
    name: http
    number: 8080

nodeSelector: {}

tolerations: []

affinity: {}
