name: Publish Helm Chart

on:
  push:
    tags:
      - v*

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: configure git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: install helm
        uses: azure/setup-helm@v3

      - uses: helm/chart-releaser-action@v1.6.0
        with:
          charts_dir: ./charts
          config: ./charts/chart-releaser.yml
        env:
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
